server:
  port: 8080
  address: 0.0.0.0

spring:
  datasource:
    url: tbd
    username: tbd
    password: tbd

  jpa:
    hibernate:
      dbl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect